/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AdvertisementListRelationFilter } from "../../advertisement/base/AdvertisementListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { FamilyMemberWhereUniqueInput } from "../../familyMember/base/FamilyMemberWhereUniqueInput";
import { StringFilter } from "../../util/StringFilter";
import { MatrimonialProfileWhereUniqueInput } from "../../matrimonialProfile/base/MatrimonialProfileWhereUniqueInput";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";

@InputType()
class UserWhereInput {
  @ApiProperty({
    required: false,
    type: () => AdvertisementListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AdvertisementListRelationFilter)
  @IsOptional()
  @Field(() => AdvertisementListRelationFilter, {
    nullable: true,
  })
  advertisements?: AdvertisementListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  email?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => FamilyMemberWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => FamilyMemberWhereUniqueInput)
  @IsOptional()
  @Field(() => FamilyMemberWhereUniqueInput, {
    nullable: true,
  })
  familyMember?: FamilyMemberWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  firstName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  lastName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => MatrimonialProfileWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => MatrimonialProfileWhereUniqueInput)
  @IsOptional()
  @Field(() => MatrimonialProfileWhereUniqueInput, {
    nullable: true,
  })
  matrimonialProfile?: MatrimonialProfileWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  profileVisible?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  role?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  username?: StringFilter;
}

export { UserWhereInput as UserWhereInput };
