/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MatrimonialProfileService } from "../matrimonialProfile.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MatrimonialProfileCreateInput } from "./MatrimonialProfileCreateInput";
import { MatrimonialProfile } from "./MatrimonialProfile";
import { MatrimonialProfileFindManyArgs } from "./MatrimonialProfileFindManyArgs";
import { MatrimonialProfileWhereUniqueInput } from "./MatrimonialProfileWhereUniqueInput";
import { MatrimonialProfileUpdateInput } from "./MatrimonialProfileUpdateInput";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MatrimonialProfileControllerBase {
  constructor(
    protected readonly service: MatrimonialProfileService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MatrimonialProfile })
  @nestAccessControl.UseRoles({
    resource: "MatrimonialProfile",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMatrimonialProfile(
    @common.Body() data: MatrimonialProfileCreateInput
  ): Promise<MatrimonialProfile> {
    return await this.service.createMatrimonialProfile({
      data: data,
      select: {
        compatibilityScore: true,
        createdAt: true,
        id: true,
        profileCompatibilityScore: true,
        profileUser: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [MatrimonialProfile] })
  @ApiNestedQuery(MatrimonialProfileFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "MatrimonialProfile",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async matrimonialProfiles(
    @common.Req() request: Request
  ): Promise<MatrimonialProfile[]> {
    const args = plainToClass(MatrimonialProfileFindManyArgs, request.query);
    return this.service.matrimonialProfiles({
      ...args,
      select: {
        compatibilityScore: true,
        createdAt: true,
        id: true,
        profileCompatibilityScore: true,
        profileUser: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MatrimonialProfile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MatrimonialProfile",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async matrimonialProfile(
    @common.Param() params: MatrimonialProfileWhereUniqueInput
  ): Promise<MatrimonialProfile | null> {
    const result = await this.service.matrimonialProfile({
      where: params,
      select: {
        compatibilityScore: true,
        createdAt: true,
        id: true,
        profileCompatibilityScore: true,
        profileUser: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MatrimonialProfile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MatrimonialProfile",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMatrimonialProfile(
    @common.Param() params: MatrimonialProfileWhereUniqueInput,
    @common.Body() data: MatrimonialProfileUpdateInput
  ): Promise<MatrimonialProfile | null> {
    try {
      return await this.service.updateMatrimonialProfile({
        where: params,
        data: data,
        select: {
          compatibilityScore: true,
          createdAt: true,
          id: true,
          profileCompatibilityScore: true,
          profileUser: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MatrimonialProfile })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MatrimonialProfile",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMatrimonialProfile(
    @common.Param() params: MatrimonialProfileWhereUniqueInput
  ): Promise<MatrimonialProfile | null> {
    try {
      return await this.service.deleteMatrimonialProfile({
        where: params,
        select: {
          compatibilityScore: true,
          createdAt: true,
          id: true,
          profileCompatibilityScore: true,
          profileUser: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/users")
  @ApiNestedQuery(UserFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async findUsers(
    @common.Req() request: Request,
    @common.Param() params: MatrimonialProfileWhereUniqueInput
  ): Promise<User[]> {
    const query = plainToClass(UserFindManyArgs, request.query);
    const results = await this.service.findUsers(params.id, {
      ...query,
      select: {
        createdAt: true,
        email: true,

        familyMember: {
          select: {
            id: true,
          },
        },

        firstName: true,
        id: true,
        lastName: true,

        matrimonialProfile: {
          select: {
            id: true,
          },
        },

        profileVisible: true,
        role: true,
        roles: true,
        updatedAt: true,
        username: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/users")
  @nestAccessControl.UseRoles({
    resource: "MatrimonialProfile",
    action: "update",
    possession: "any",
  })
  async connectUsers(
    @common.Param() params: MatrimonialProfileWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        connect: body,
      },
    };
    await this.service.updateMatrimonialProfile({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/users")
  @nestAccessControl.UseRoles({
    resource: "MatrimonialProfile",
    action: "update",
    possession: "any",
  })
  async updateUsers(
    @common.Param() params: MatrimonialProfileWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        set: body,
      },
    };
    await this.service.updateMatrimonialProfile({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/users")
  @nestAccessControl.UseRoles({
    resource: "MatrimonialProfile",
    action: "update",
    possession: "any",
  })
  async disconnectUsers(
    @common.Param() params: MatrimonialProfileWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        disconnect: body,
      },
    };
    await this.service.updateMatrimonialProfile({
      where: params,
      data,
      select: { id: true },
    });
  }
}
